<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'ZipStream\\' => array($vendorDir . '/maennchen/zipstream-php/src'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'PhpOffice\\PhpSpreadsheet\\' => array($vendorDir . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet'),
    'OC\\Core\\' => array($baseDir . '/core'),
    'OC\\' => array($baseDir . '/lib/private'),
    'OCP\\' => array($baseDir . '/lib/public'),
    'Matrix\\' => array($vendorDir . '/markbaker/matrix/classes/src'),
    'Complex\\' => array($vendorDir . '/markbaker/complex/classes/src'),
    '' => array($baseDir . '/lib/private/legacy'),
);
